---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aap2-cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ansible-automation-platform
  - kind: ServiceAccount
    name: ac-tower
    namespace: ansible-automation-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin