---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:privileged'
  namespace: ansible-automation-platform
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ansible-automation-platform
  - kind: ServiceAccount
    name: ac-tower
    namespace: ansible-automation-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'