// Module included in the following assemblies:
//
// * scalability_and_performance/ztp-factory-install-clusters.adoc
:_content-type: PROCEDURE
[id="configuring-edge-cluster-at-remote-location_{context}"]
= Configuring the edge cluster at the remote location
include::modules/common-attributes.adoc[]

Configure the edge cluster by using the custom user interface.

[NOTE]
====
Some of the commands need `root` access to run. You can either log in as the `root` user and proceed with the step or add `sudo` before every command.
====

.Prerequisites

* `kubeadmin` password as supplied by vendor.
* URL of the custom user interface.

.Procedure

. Unbox and turn on the cluster.

. Log in at the command line to `master-0` of the cluster:

. Configure DNS on `master-0` of the hub cluster:

.. Edit `resolv.conf` on `master-0` and add the IP address of `master-0`.
+
[source,terminal]
----
$ vi /etc/resolv.conf
----

.. Add the line.
+
[source,terminal]
----
nameserver 192.168.7.10
----

. Configure a static IP on the connected laptop:

.. Determine the name of the laptop's network interface card (NIC) as follows.
+
[source,terminal]
----
$ ip addr
----
+
[NOTE]
====
Look for the NIC name starting with the letter `e`.
====

.. Edit the NIC's network configuration.
+
[source,terminal]
----
$ vi /etc/sysconfig/network-scripts/ifcfg-eth0
----
+
[NOTE]
====
Here `eth0` is the network card name, and it can be different for different computers.
====

.. Add or modify the configuration below:
+
[source,terminal]
----
BOOTPROTO=static
IPADDR=192.168.7.21
NETMASK=255.255.255.0
GATEWAY=192.168.0.1
DNS1=192.168.7.10
----
+
[NOTE]
====
Use any IP in the range `192.168.7.20 - 192.168.7.150`.
====

. Restart the network services:
+
[source,terminal]
----
$ systemctl restart NetworkManager
----

. Open a browser and log in to the edge cluster configuration user interface at the following URL with the supplied `kubeadmin` `username` and `password`:
+
[source,terminal]
----
https://edge-cluster-setup.example-edge-cluster.domain.com
----
+
[NOTE]
====
This `kubeadmin` username and password was created at the factory and should have been supplied to you. Only one user is initially created.
====

. Click **Continue**.

. Step through the screens to complete the initial setup.

.. In the first two screens create a new user account by entering a `username` and `password` when prompted.
+
[NOTE]
====
This new user account is granted `cluster-admin` privileges and should be used rather than the factory created `kubeadmin` account.
====

.. In the **API** screen assign the IP address that will be used for API traffic. A default value is assigned but you are free to update this.

.. In the **Ingress** screen assign the IP address that will be used for new routes and traffic managed by the ingress controller. A default value is assigned but you are free to update this.

.. Optional: Enter the name of base domain for your edge cluster (e.g. yourdomain.com)
+
[NOTE]
====
The new and the old domain names should be both properly configured in DNS.
Aditional screen will be displayed for chosing how to create certificates for the new domain.
When **Automatic** method is selected (default), then all the certificates will be automatically generated and assigned.
If **Manual** method is selected, then we can chose between uploading or automatically generating specific certificates.
====

.. Click **Download** in the **Download your private SSH key** screen and download the edge cluster private SSH key.
+
[NOTE]
====
You need this to access the nodes of the edge cluster.
====

.. Click **Finish setup**.
+
[NOTE]
====
This will initiate the process of applying changes to the edge cluster. It might take several minutes for the cluster to reconcile.
If the domain name was not changed, then upon success you should get to a page with "Setup complete!" at the top.
In case the domain name was changed, you will be redirected to the edge-cluster-setup page of the new domain, where you will have to login agan.
====

.. Under **Settings** you have the option to delete the kubeadmin user and to change the values of the **API address**, **Ingress address** and the previously configured **Domain**.
+
[NOTE]
====
Deleting the kubeadmin user is recommended. This action is irreversible.
At this stage you will not be prompted for a username and password as you are already logged in as `kubeadmin`.
====

.. Click **Log out** in the top right hand corner. This concludes working with the edge cluster configuration user interface.

. Log in to the web console of your edge cluster.

. Select the newly created identity provider `ztpfw-htpasswd-idp`.

. In the cluster log in screen enter the `username` and `password` created in step 8a.

. After you access the cluster, register your cluster subscription with the following steps:

.. link:https://cloud.redhat.com/[Log in to the console] to register the disconnected OpenShift cluster. See link:https://access.redhat.com/solutions/4930131[How to register disconnected OpenShift Container Platform 4 cluster on cloud.redhat.com] for details.

.. Obtain the pull secret from link:https://console.redhat.com/openshift/downloads[Pull secret], which can be found under `Tokens`.

.. Change the global pull secret. Follow the guidance in link:https://access.redhat.com/solutions/4902871[How to change the global pull secret in OCP 4] to do that.

Your cluster is now registered to {cluster-manager-first} and entitled to Red Hat subscription management.
