// Module included in the following assemblies:
//
// * scalability_and_performance/ztp-factory-install-clusters.adoc
:_content-type: PROCEDURE
[id="monitoring-the-progress-of-the-edge-cluster-factory-install_pipeline_{context}"]
= Monitoring the progress of the edge cluster factory install pipeline
include::modules/common-attributes.adoc[]

You can watch the progress of the pipelines by using the {product-title} web console and by using the deployment log file.

.Procedure

. Examine the logs to watch the progress of the `deploy-ztp-edgeclusters`.
+
[source,terminal]
----
$ tkn pipeline logs deploy-ztp-edgecluster-run-2rklt -f -n edgecluster-deployer
----
. Log in to the {product-title} web console.
. Navigate to *Pipelines* -> *Pipelines* and select the Project *edgecluster-deployer*.
+
[NOTE]
====
The `edgecluster-deployer` pipeline stores all the artefacts for {product-title} Pipelines.
====
. Select **PipelineRuns** to drill down into the details of the pipeline runs.

. The stages of the pipeline are clearly shown and you can select each in turn to view the logs associated with that stage of the deployment.
