// Module included in the following assemblies:
//
// * scalability_and_performance/ztp-factory-install-clusters.adoc
:_content-type: PROCEDURE
[id="installing-the-openshift-pipelines-operator_{context}"]
= Installing the OpenShift Pipelines Operator
include::modules/common-attributes.adoc[]

Follow this guidance to install the OpenShift Pipelines Operator that is used to run the pipeline.

.Prerequisites

* An installed {product-title} hub cluster.
* Install the OpenShift CLI (`oc`).
* Access to the cluster as a user with the `cluster-admin` role.
* Install `git`. For guidance on installing `git`, see link:https://github.com/git-guides/install-git[Install Git].

.Procedure

. Export the `KUBECONFIG` environment variable:
+
[source,terminal]
----
$ export KUBECONFIG=<path_to_kubeconfig>/kubeconfig
----

. Run the following bash script `bootstrap.sh` with the `KUBECONFIG` as a parameter to install the OpenShift Pipelines Operator:
+
[source,terminal]
----
$ curl -sL https://raw.githubusercontent.com/rh-ecosystem-edge/ztp-pipeline-relocatable/main/pipelines/bootstrap.sh | bash -s -- ${KUBECONFIG}
----
+
This script:

* Installs the `tkn` CLI. This tool manages {product-title} pipelines from a terminal.
* Clones the link:https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable[ztp-pipeline-relocatable] pipeline repository.
* Checks that the correct permissions are set on the hub cluster.
* Deploys the OpenShift Pipelines Operator from the Operator Lifecycle Manager (OLM) catalog.
* Creates ZTP pipelines and the associated tasks.

. Optional: Monitor the progress in the terminal window(a) and/or in the web console(b).

.. In the terminal window you are expected to see an output similar to the following:
+
[source,terminal]
----
>>>> Creating NS edgecluster-deployer and giving permissions to SA edgecluster-deployer
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
namespace/edgecluster-deployer configured
serviceaccount/edgecluster-deployer configured
clusterrolebinding.rbac.authorization.k8s.io/cluster-admin-0 configured

>>>> Cloning Repository into your local folder
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Cloning into 'ztp-pipeline-relocatable'...
remote: Enumerating objects: 3824, done.
remote: Counting objects: 100% (1581/1581), done.
remote: Compressing objects: 100% (963/963), done.
remote: Total 3824 (delta 963), reused 1163 (delta 589), pack-reused 2243
Receiving objects: 100% (3824/3824), 702.12 KiB | 8.46 MiB/s, done.
Resolving deltas: 100% (2182/2182), done.

>>>> Deploying Openshift Pipelines
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
subscription.operators.coreos.com/openshift-pipelines-operator-rh unchanged
>>>> Waiting for: Openshift Pipelines
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>>>> Deploying ZTPFW Pipelines and tasks
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
pipeline.tekton.dev/deploy-ztp-hub configured
pipeline.tekton.dev/deploy-ztp-edgeclusters configured
task.tekton.dev/common-pre-flight configured
task.tekton.dev/hub-deploy-mce configured
task.tekton.dev/hub-deploy-disconnected-registry configured
task.tekton.dev/hub-deploy-httpd-server configured
task.tekton.dev/hub-deploy-hub-config configured
task.tekton.dev/hub-deploy-icsp-hub configured
task.tekton.dev/hub-save-config configured
task.tekton.dev/edgecluster-deploy-disconnected-registry-edgeclusters configured
task.tekton.dev/edgecluster-deploy-icsp-edgeclusters-post configured
task.tekton.dev/edgecluster-deploy-icsp-edgeclusters-pre configured
task.tekton.dev/edgecluster-deploy-metallb configured
task.tekton.dev/edgecluster-deploy-ocs configured
task.tekton.dev/edgecluster-deploy-edgecluster configured
task.tekton.dev/edgecluster-deploy-workers configured
task.tekton.dev/edgecluster-detach-cluster configured
task.tekton.dev/edgecluster-restore-hub-config configured
----

.. Log in to the {product-title} web console.

... Navigate to *Pipelines* -> *Pipelines*.

... Select the project *edgecluster-deployer*.
+
[NOTE]
====
Stored in the `edgecluster-deployer` namespace are all the artifacts for the successful execution of the pipelines. Monitor the progress of the pipelines in this window.
====
