// Module included in the following assemblies:
//
// * scalability_and_performance/ztp-factory-install-clusters.adoc
:_content-type: PROCEDURE
[id="post-edgecluster-factory-pipeline-verification-checks_{context}"]
= Post edge cluster factory pipeline verification checks
include::modules/common-attributes.adoc[]

Perform the following steps after completion of the edge cluster factory pipeline run.

.Prerequisites

* An {product-title} hub cluster.
* Log in as a user with `cluster-admin` privileges.

.Procedure

. Verify MetalLB is successfully installed:
+
[source,terminal]
----
$ oc get addresspool -A
----
+
.Example output
+
[source,terminal]
----
NAMESPACE       NAME                AGE
metallb         api-public-ip       10m
metallb         ingress-public-ip   10m
----

. Confirm that the `NodeNetworkConfigurationPolicy` has been applied to the cluster:
+
[source,terminal]
----
$ oc get nncp -A
----
+
.Example output
+
[source,terminal]
----
NAME                                    STATUS
kubeframe-edgecluster-0-master-0-nccp         Available
kubeframe-edgecluster-0-master-1-nccp         Available
kubeframe-edgecluster-0-master-2-nccp         Available
----

. Verify the internal registry is running:
+
[source,terminal]
----
$ oc get pod -n ztpfw-registry
----
+
.Expected output
+
[source,terminal]
----
NAME                          READY   STATUS      RESTART         AGE
ztpfw-registry-77ff664d47     1/1     RUNNING     0               151m
----

. Run the following command to review the pipeline run and verify the steps that were executed:
+
[NOTE]
====
This shows the duration of every step, the parameters supplied to the pipeline. It also highlights any issues during the execution of the pipeline.
====
+
[source,terminal]
----
$ tkn pr describe deploy-ztp-edgecluster-run-2rklt -n edgecluster-deployer
----
