// Module included in the following assemblies:
//
// * scalability_and_performance/ztp-factory-install-clusters.adoc
:_content-type: PROCEDURE
[id="running-the-hub-cluster-factory-install-pipeline_{context}"]
= Running the hub cluster factory install pipeline
include::modules/common-attributes.adoc[]

The edge pipeline performs a series of steps to deploy an Edge Cluster, review the following sections on the requirements and the procedure.

.Prerequisites

* An installed {product-title} hub cluster.
* Access to the cluster as a user with the `cluster-admin` role.

.Procedure

. Create a file `edgeclusters.yaml` with sample details as shown. A sample configuration file is present in `examples/config.yaml`.
+
[NOTE]
====
At this stage you only need to build out the `config` section. The `config` section specifies the cluster configuration values used to install and configure the hub and edge cluster.
====
+
[source,yaml]
----
config:
  OC_OCP_VERSION: "4.10.24"
  OC_ACM_VERSION: "2.5" <2>
  OC_ODF_VERSION: "4.10" <3>
----
+
<1> {product-title} version of the edge cluster.
<2> Red Hat Advanced Cluster Management (RHACM) version. Note that ACM 2.5 when using the `mce` pipeline, will deploy MCE 2.0
<3> The OpenShift Data Foundation (ODF) version.

. Start the hub cluster pipeline from the command line:
+
[source,terminal]
----
$ tkn pipeline start -n edgecluster-deployer edgeclusters-config="$(cat /path-to-edgecluster.yaml/edgeclusters.yaml)" -p kubeconfig=${KUBECONFIG} -w=ztp,claimName=ztp-pvc --timeout 5h --use-param-defaults deploy-ztp-hub<1>
----
+
<1> Note that there are different pipeline runs available (`deploy-ztp-hub` and `deploy-ztp-hub-mce`)

[NOTE]
====
This command starts the hub cluster pipeline in the namespace `edgecluster-deployer` with the defined edge cluster configuration and the `kubeconfig` in the workspace `ztp` with the previously configured persistent storage claim `ztp-pvc`. A timeout of 5 hours is set for the execution of the `deploy-ztp-hub` with all other parameters set to the default.
====
+
.Example output
[source,terminal]
----
PipelineRun started: deploy-ztp-hub-run-2h44k

In order to track the PipelineRun progress run:
tkn pipelinerun logs deploy-ztp-hub-run-2h44k -f -n edgecluster-deployer
----
