[id="ztp-for-factory-prerequisites"]
= Prerequisites
include::modules/common-attributes.adoc[]
:context: ztp-for-factory-prerequisites

toc::[]

Installer-provisioned installation of {product-title} requires:

. OpenShift Cluster with 3 masters
    . All Cluster Operators in good health status
. PVC's defined for the HUB
. Ability to add DNS entries
    . `httpd-server.apps.CLUSTER.DOMAIN`
    . `kubeframe-registry-kubeframe-registry.apps.CLUSTER.DOMAIN`
. `spokes.yaml` file with the configuration for the spokes

Of course, the requirements for the installation of {product-title} are also to be satisfied on the hardware involved in the installation.



### The Spokes YAMl file

## Lab testing

This section will cover two aspects of the testing, the HUB and the Spokes

### Hub

We internally use the files in the folder `hack/deploy` to virtually setup an environment to test the pipeline.

The first step is the `build-hub.sh` which builds the hab deployment with all the requirements (hub, DNS, PVC's, spokes.yaml, etc.) that will be later used with OpenShift Pipelines to perform all the tests.

### Spokes

## Usage

### OpenShift Pipelines installation

First we need to install OpenShift Pipelines Operator that will be used for running the pipeline, this is achieved by using a bootstrapping script that will install the Operator and the CR to initiate the deployment.

This script will also create the required pipeline definitions and tasks.

### Pipeline execution Hub

```sh
tkn XXXXX
```

### Pipeline execution Spoke

### Monitoring

You can follow the pipeline execution via XXXXX
