// Module included in the following assemblies:
//
// * scalability_and_performance/ztp-factory-install-clusters.adoc
:_content-type: CONCEPT
[id="about-the-factory-install_pipeline_{context}"]
= About the factory install pipeline
include::modules/common-attributes.adoc[]

The factory install pipelines build out your factory environment (hub and edge clusters) for the edge cluster to reach a state of readiness to be shipped off site. Red Hat has created a set of community scripts to help you get started with this task.

A GitHub repository contains all the relevant scripts and YAML files you need to provision the hub cluster and edge clusters.

The edge cluster installation uses a zero touch provisioning (ZTP) approach facilitated by {rh-mce-first} using the Assisted Installer (AI) installed as part of running the factory install pipeline.

With ZTP and AI, you can provision many {product-title} edge clusters in a factory-type setting. MCE manages clusters in a hub and edge architecture, where a single hub cluster manages many edge clusters. A hub cluster running MCE provisions and deploys the edge clusters using ZTP and AI. AI provisions {product-title} on the bare-metal edge clusters.
