apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: spoke-deploy-disconnected-registry-spokes
  namespace: spoke-deployer
  annotations:
    description: |
      This task will deploy the Disconnected Internal registry.
      Then will perform the OCP and OLM sync, based on the SYNC parameter.
      If this sync parameter is YES, allows the spoke to sync with RedHat Registry for OCP and OLM.
      If this sync parameter is NO, it will download the Tarball from the HTTPD server created on the Hub pipeline.
      Update the Global PullSecret for every spoke with the proper credentials.
spec:
  workspaces:
    - name: ztp
  params:
    - name: ztp-tag
      type: string
      default: "latest"
    - name: config-file-path
      type: string
      default: ""
    - name: spokes-config
      type: string
      default: ""
    - name: sync
      type: string
      default: "no"
  stepTemplate:
    env:
      - name: WORKDIR
        value: "/ztp-pipeline"
      - name: SPOKES_CONFIG
        value: $(params.spokes-config)
      - name: KUBECONFIG
        value: "$(workspaces.ztp.path)/kubeconfig"
      - name: DEPLOY_REGISTRY_DIR
        value: "deploy-disconnected-registry"
      - name: SYNC
        value: $(params.sync)

  steps:
    - name: deploy-disconnected-registry
      image: "quay.io/flaper87/ztp-pipeline:$(params.ztp-tag)"
      imagePullPolicy: Always
      script: |
        #!/usr/bin/bash

        cd ${WORKDIR}/${DEPLOY_HTTPD_SERVER_DIR}
        ./deploy.sh 'spoke'

    - name: mirror-olm-and-ocp
      image: "quay.io/flaper87/ztp-pipeline:$(params.ztp-tag)"
      imagePullPolicy: Always
      script: |
        #!/usr/bin/bash

        cd ${WORKDIR}/${DEPLOY_HTTPD_SERVER_DIR}

        if [ "${SYNC}" == "yes" ]; then
          echo "Starting Image Mirroring of OCP and OLM Step on the Spoke Cluster"
          ./ocp-sync.sh 'spoke'
          ./olm-sync.sh 'spoke'
        else
          echo "Mirror OCP and OLM Step Avoided, Using Tarball"
          ./mirror-snapshot.sh 'spoke'
        fi

    - name: update-global-pullsecret
      image: "quay.io/flaper87/ztp-pipeline:$(params.ztp-tag)"
      imagePullPolicy: Always
      script: |
        #!/usr/bin/bash

        cd ${WORKDIR}/${DEPLOY_HTTPD_SERVER_DIR}
        ./update-global-pullsecret.sh 'spoke'
