apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: spoke-deploy-metallb
  namespace: spoke-deployer
  annotations:
    description: |
      This task will deploy MetalLB on the Spoke Cluster.
spec:
  workspaces:
    - name: ztp
  params:
    - name: ztp-tag
      type: string
      default: "latest"
    - name: config-file-path
      type: string
      default: ""
    - name: spokes-config
      type: string
      default: ""
  stepTemplate:
    env:
      - name: WORKDIR
        value: "/ztp-pipeline"
      - name: SPOKES_CONFIG
        value: $(params.spokes-config)
      - name: KUBECONFIG
        value: "$(workspaces.ztp.path)/kubeconfig"
      - name: DEPLOY_METALLB_DIR
        value: "deploy-metallb"
  steps:
    - name: deploy-metallb
      image: "quay.io/flaper87/ztp-pipeline:$(params.ztp-tag)"
      imagePullPolicy: Always
      script: |
        #!/usr/bin/bash

        cd ${WORKDIR}/${DEPLOY_METALLB_DIR}
        ./deploy.sh
