apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: spoke-restore-hub-config
  namespace: spoke-deployer
  annotations:
    description: |
      This task will recover the data saved from teh Hub in the Hub Pipeline and put it on the pod to be consumed by the tasks
spec:
  workspaces:
    - name: ztp
  params:
    - name: ztp-tag
      type: string
      default: "latest"
    - name: config-file-path
      type: string
      default: ""
    - name: spokes-config
      type: string
      default: ""
  stepTemplate:
    env:
      - name: WORKDIR
        value: "/ztp-pipeline"
      - name: SPOKES_CONFIG
        value: $(params.spokes-config)
      - name: KUBECONFIG
        value: "$(workspaces.ztp.path)/kubeconfig"
      - name: RO_SPOKE_FOLDER
        value: "/root/ztp-build-hub/"
  steps:
    - name: restore-hub-config
      image: "quay.io/flaper87/ztp-pipeline:$(params.ztp-tag)"
      imagePullPolicy: Always
      script: |
        #!/usr/bin/bash
        # TODO: We need to mount a volume in the pod in order to have those files available among
        # different steps, in the spoke should be RO.

        rsync -avr --progress --delete ${RO_SPOKE_FOLDER}/* ${WORKDIR}/build/ 
