apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  namespace: openshift-storage
  name: odf-lvm-operator
spec:
  channel: "stable-{{ .Version }}"
  installPlanApproval: Automatic
  name: lvms-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
