apiVersion: helm.openshift.io/v1beta1
kind: HelmChartRepository
metadata:
  name: emberstack-helm-charts
spec:
  connectionConfig:
    url: 'https://emberstack.github.io/helm-charts'
  name: Emberstack Helm Charts