# Add 'repo' label to any root file changes
repo:
  - ./*

# documentation
documentation:
  - documentation/**/*
  - website/**/*
  - utils/**/*
  - examples/**/*

# internal components
internal:
  - hack/**/*
  - .github/workflows/**/*
  - shared-utils/**/*
  - hack/set-motd/**/*

## actions, pipelines and workflows
github-actions:
  - .github/**/*

pipelines:
  - pipelines/**/*
  - images/Containerfile.pipeline

## ansible
ansible:
  - hack/deploy-hub-local/ansible/**/*
  - .github/workflows/ci-test-ansible.yml

# ztpfw-ui components
ui:
  - deploy-ui/**/*
  - ui/**/*
  - images/Containerfile.UI
  - .github/workflows/ui.yml

test-ci-ui:
  - deploy-ui/**/*
  - ui/**/*
  - images/Containerfile.UI
  - .github/workflows/ui.yml

# ztpfw-core components
acm:
  - deploy-acm/**/*

registry:
  - deploy-disconnected-registry/**/*

metallb:
  - deploy-metallb/**/*

edgecluster:
  - deploy-edgecluster/**/*

worker:
  - deploy-worker/**/*

odf:
  - deploy-odf/**/*

finalization:
  - finish-deployment/**/*

hubconfig:
  - deploy-hub-config/**/*

contrib:
  - contrib/**/*

images:
  - images/**/*
