apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: edgecluster-deploy-metallb
  annotations:
    description: |
      This task will deploy MetalLB on the Edge-cluster Cluster.
spec:
  workspaces:
    - name: ztp
  params:
    - name: ztp-container-image
      type: string
      default: "quay.io/ztpfw/pipeline:latest"
    - name: pipeline-name
      type: string
      default: $(context.taskRun.name)
    - name: edgeclusters-config
      type: string
      default: ""
    - name: mock
      type: string
      default: "false"
    - name: ztp-extra-args
      type: string
      default: ""
  steps:
    - name: deploy-metallb
      image: "$(params.ztp-container-image)"
      imagePullPolicy: Always
      script: |
        #!/usr/bin/bash

        if [[ "$(params.mock)" == 'false' ]]; then
          ztp create metallbs \
          --config "$(params.edgeclusters-config)" \
          --log-field "$(params.pipeline-name)" \
          --log-field "$(context.taskRun.name)" \
          --wait "30m" \
          $(params.ztp-extra-args)
        else
          echo "Deploy MetalLB: Mock mode on"
        fi
