apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: edgecluster-deploy-icsp-edgeclusters-post
  annotations:
    description: |
      This task will deploy the ICSP on the edgecluster cluster to point to the disconnected registry deployed in the previous step.
spec:
  workspaces:
    - name: ztp
  params:
    - name: ztp-container-image
      type: string
      default: "quay.io/ztpfw/pipeline:latest"
    - name: kubeconfig
      type: string
      default: ""
    - name: pipeline-name
      type: string
      default: "all"
    - name: edgeclusters-config
      type: string
      default: ""
    - name: mock
      type: string
      default: "false"
  stepTemplate:
    env:
      - name: WORKDIR
        value: "/workspace/ztp"
      - name: OUTPUTDIR
        value: "/workspace/ztp/$(params.pipeline-name)/$(context.taskRun.name)"
      - name: EDGECLUSTERS_CONFIG
        value: $(params.edgeclusters-config)
      - name: KUBECONFIG
        value: "$(workspaces.ztp.path)/kubeconfig"
      - name: DEPLOY_EDGECLUSTERS_DIR
        value: "deploy-edgecluster"
      - name: DEPLOY_REGISTRY_DIR
        value: "deploy-disconnected-registry"
      - name: SHARED_DIR
        value: "shared-utils"
      - name: MOCK
        value: $(params.mock)
  steps:
    - name: deploy-icsp-edgeclusters-post
      image: "$(params.ztp-container-image)"
      imagePullPolicy: Always
      script: |
        #!/usr/bin/bash

        if [[ "${MOCK}" == 'false' ]]; then
          cd ${WORKDIR}/${DEPLOY_EDGECLUSTERS_DIR}
          ./configure_disconnected.sh 'edgecluster' 'post'
        else
          echo "Deploy ICSP Post: Mock mode on"
        fi
