apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: edgecluster-deploy-disconnected-registry-edgeclusters-olm
  annotations:
    description: |
      Will perform the OCP and OLM sync, based on the SYNC parameter.
spec:
  workspaces:
    - name: ztp
  params:
    - name: ztp-container-image
      type: string
      default: "quay.io/ztpfw/pipeline:latest"
    - name: kubeconfig
      type: string
      default: ""
    - name: pipeline-name
      type: string
      default: $(context.taskRun.name)
    - name: edgeclusters-config
      type: string
      default: ""
    - name: mock
      type: string
      default: "false"
  stepTemplate:
    env:
      - name: WORKDIR
        value: "/workspace/ztp/$(params.pipeline-name)"
      - name: OUTPUTDIR
        value: "/workspace/ztp/$(params.pipeline-name)/build/$(context.taskRun.name)"
      - name: EDGECLUSTERS_CONFIG
        value: $(params.edgeclusters-config)
      - name: KUBECONFIG
        value: "$(workspaces.ztp.path)/kubeconfig"
      - name: DEPLOY_REGISTRY_DIR
        value: "deploy-disconnected-registry"
      - name: SHARED_DIR
        value: "shared-utils"
      - name: MOCK
        value: $(params.mock)
  steps:

    - name: mirror-olm
      image: "$(params.ztp-container-image)"
      imagePullPolicy: Always
      securityContext:
        capabilities:
          add: ["SETFCAP"]
        privileged: true
        runAsUser: 0
      volumeMounts:
      - mountPath: /var/lib/containers
        name: lib-containers
      script: |
        #!/usr/bin/bash

        if [[ "${MOCK}" == 'false' ]]; then
          cd ${WORKDIR}/${DEPLOY_REGISTRY_DIR}
          echo "Starting OLM Catalog Image Mirroring Step"
          ./olm-sync.sh 'edgecluster'
        else
          echo "Deploy Mirror OLM Edge-cluster: Mock mode on"
        fi


  volumes:
  - name: lib-containers
    emptyDir: {}
