apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: edgecluster-deploy-edgecluster
  annotations:
    description: |
      This task will deploy the edgeclusters based on the edgeclusters.yaml file passed to the pipeline/task.
spec:
  workspaces:
    - name: ztp
  params:
    - name: ztp-container-image
      type: string
      default: "quay.io/ztpfw/pipeline:latest"
    - name: pipeline-name
      type: string
      default: $(context.taskRun.name)
    - name: edgeclusters-config
      type: string
      default: ""
    - name: mock
      type: string
      default: "false"
    - name: ztp-extra-args
      type: string
      default: ""
  stepTemplate:
    env:
      - name: MOCK
        value: $(params.mock)
  steps:
    - name: deploy-edgeclusters
      image: "$(params.ztp-container-image)"
      imagePullPolicy: Always
      script: |
        #!/usr/bin/bash

        if [[ "${MOCK}" == 'false' ]]; then
          ztp create clusters \
          --config "$(params.edgeclusters-config)" \
          --output "/workspace/ztp/$(params.pipeline-name)" \
          --wait "2h30m" \
          --log-field "pr=$(params.pipeline-name)" \
          --log-field "tr=$(context.taskRun.name)" \
          $(params.ztp-extra-args)
        else
          echo "Deploy Edge-cluster: Mock mode on"
        fi
