---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: $SVC_NAME
  namespace: metallb
spec:
  autoAssign: false
  addresses:
    - $METALLB_IP/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: $SVC_NAME
  namespace: metallb
spec:
  ipAddressPools:
  - $SVC_NAME
