kind: ConfigMap
apiVersion: v1
metadata:
  namespace: {{ .Cluster.Name }}
  name: {{ .Cluster.Name }}-manifests-override
  annotations:
    manifests-directory: manifests
data:
  cluster-network-03-config.yml: {{ execute "files/cluster-network-03-config.yml" . | json }}
