apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Cluster.Name }}
  name: {{ .Cluster.Name }}-keypair
data:
  id_rsa.pub: {{ .Cluster.SSH.PublicKey | base64 }}
  id_rsa.key: {{ .Cluster.SSH.PrivateKey | base64 }}