apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hub-deploy-update-global-ps
  annotations:
    description: |
      This task will deploy the Disconnected Internal registry.
      Then will perform the OCP and OLM sync.
      Update the Global PullSecret for every edgecluster with the proper credentials
      and in the end create a Tarball to be shared with every edgecluster provisioned.
spec:
  workspaces:
    - name: ztp
  params:
    - name: ztp-container-image
      type: string
      default: "quay.io/ztpfw/pipeline:latest"
    - name: kubeconfig
      type: string
      default: ""
    - name: pipeline-name
      type: string
      default: $(context.taskRun.name)
    - name: edgeclusters-config
      type: string
      default: ""
    - name: mock
      type: string
      default: "false"
  stepTemplate:
    env:
      - name: WORKDIR
        value: "/workspace/ztp/$(params.pipeline-name)"
      - name: OUTPUTDIR
        value: "/workspace/ztp/$(params.pipeline-name)/build/$(context.taskRun.name)"
      - name: EDGECLUSTERS_CONFIG
        value: $(params.edgeclusters-config)
      - name: KUBECONFIG
        value: "$(workspaces.ztp.path)/kubeconfig"
      - name: DEPLOY_REGISTRY_DIR
        value: "deploy-disconnected-registry"
      - name: SHARED_DIR
        value: "shared-utils"
      - name: MOCK
        value: $(params.mock)
  steps:
    - name: update-global-pullsecret
      image: "$(params.ztp-container-image)"
      imagePullPolicy: Always
      securityContext:
        capabilities:
          add: ["SETFCAP"]
      script: |
        #!/usr/bin/bash

        if [[ "${MOCK}" == 'false' ]]; then
          cd ${WORKDIR}/${DEPLOY_REGISTRY_DIR}
          ./update-global-pullsecret.sh 'hub'
        else
          echo "Mirror Update Pull Secret: Mock mode on"
        fi
