apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hub-deploy-aap
  annotations:
    description: |
      This task will deploy Ansible Automation Platform on the Hub Cluster.
spec:
  workspaces:
    - name: ztp
  params:
    - name: ztp-container-image
      type: string
      default: "quay.io/ztpfw/pipeline:latest"
    - name: kubeconfig
      type: string
      default: ""
    - name: spokes-config
      type: string
      default: ""
    - name: mock
      type: string
      default: "false"
  stepTemplate:
    env:
      - name: WORKDIR
        value: "/workspace/ztp"
      - name: SPOKES_CONFIG
        value: $(params.spokes-config)
      - name: KUBECONFIG
        value: "$(workspaces.ztp.path)/kubeconfig"
      - name: DEPLOY_AAP_DIR
        value: "deploy-aap"
      - name: SHARED_DIR
        value: "shared-utils"
      - name: MOCK
        value: $(params.mock)
  steps:
    - name: deploy-hub-config
      image: "$(params.ztp-container-image)"
      imagePullPolicy: Always
      script: |
        #!/usr/bin/bash

        if [[ "${MOCK}" == 'false' ]]; then
          cd ${WORKDIR}/${DEPLOY_AAP_DIR}
          ./deploy.sh
        else
          ls -lath ${WORKDIR}/
          echo "Deploy Ansible Automation Platform Mock mode on"
        fi
