apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hub-deploy-acm
  annotations:
    description: |
      This task will deploy RHACM on the Hub Cluster.
spec:
  workspaces:
    - name: ztp
  params:
    - name: ztp-container-image
      type: string
      default: "quay.io/ztpfw/pipeline:latest"
    - name: kubeconfig
      type: string
      default: ""
    - name: spokes-config
      type: string
      default: ""
    - name: mock
      type: bool
      default: false
  stepTemplate:
    env:
      - name: WORKDIR
        value: "/workspace/ztp"
      - name: SPOKES_CONFIG
        value: $(params.spokes-config)
      - name: KUBECONFIG
        value: "$(workspaces.ztp.path)/kubeconfig"
      - name: DEPLOY_ACM_DIR
        value: "deploy-acm"
      - name: SHARED_DIR
        value: "shared-utils"
      - name: MOCK
        value: $(params.mock)
  steps:
    - name: deploy-acm
      image: "$(params.ztp-container-image)"
      imagePullPolicy: Always
      script: |
        #!/usr/bin/bash

        if [[ ! ${MOCK} ]]; then
          cd ${WORKDIR}/${DEPLOY_ACM_DIR}
          ./deploy.sh
        else
          echo "Deploy ACM: Mock mode on"
        fi
