apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hub-deploy-httpd-server 
  annotations:
    description: |
      This task will deploy the HTTPD server to host the RHCOS Images and the Images Tarball.
spec:
  workspaces:
    - name: ztp
  params:
    - name: ztp-container-image
      type: string
      default: "quay.io/jparrill/ztp-pipeline:latest"
    - name: kubeconfig 
      type: string
      default: ""
    - name: spokes-config
      type: string
      default: ""
  stepTemplate:
    env:
      - name: WORKDIR
        value: "/ztp-pipeline"
      - name: SPOKES_CONFIG
        value: $(params.spokes-config)
      - name: KUBECONFIG
        value: "$(workspaces.ztp.path)/kubeconfig"
      - name: DEPLOY_HTTPD_SERVER_DIR
        value: "deploy-httpd-server"
  steps:
    - name: hub-deploy-httpd-server
      image: "$(params.ztp-container-image)"
      imagePullPolicy: Always
      script: |
        #!/usr/bin/bash

        cd ${WORKDIR}/${DEPLOY_HTTPD_SERVER_DIR}
        ./deploy.sh
