apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hub-deploy-icsp-hub
  annotations:
    description: |
      This task will deploy RHACM on the Hub Cluster.
spec:
  workspaces:
    - name: ztp
  params:
    - name: ztp-container-image
      type: string
      default: "quay.io/jparrill/ztp-pipeline:latest"
    - name: config-file-path
      type: string
      default: ""
    - name: spokes-config
      type: string
      default: ""
  stepTemplate:
    env:
      - name: WORKDIR
        value: "/ztp-pipeline"
      - name: SPOKES_CONFIG
        value: $(params.spokes-config)
      - name: KUBECONFIG
        value: "$(workspaces.ztp.path)/kubeconfig"
      - name: DEPLOY_SPOKES_DIR
        value: "deploy-spoke"
  steps:
    - name: deploy-icsp-hub
      image: "$(params.ztp-container-image)"
      imagePullPolicy: Always
      script: |
        #!/usr/bin/bash

        cd ${WORKDIR}/${DEPLOY_SPOKES_DIR}
        ./configure_disconnected.sh 'hub'
