resources:
  - hub-deploy-acm.yaml
  - hub-deploy-disconnected-registry.yaml
  - hub-deploy-httpd-server.yaml
  - hub-deploy-hub-config.yaml
  - hub-deploy-icsp.yaml
  - hub-save-config.yaml
  - hub-deploy-aap.yaml
  - hub-deploy-argocd.yaml
  - hub-deploy-gitea.yaml
