apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-ztp-spokes
  namespace: spoke-deployer 
spec:
  description: Tekton Pipeline to deploy Kubeframe Spokes clusters
  params:
    - name: ztp-tag
      type: string
      default: "latest"
    - name: kubeconfig
      type: string
    - name: spokes-config
      type: string
    - name: sync
      type: string
      default: "no"
  workspaces:
    - name: ztp
  tasks:

  # Preflight
  - name: pre-flight
    taskRef:
      name: common-pre-flight 
    params:
      - name: spokes-config
        value: $(params.spokes-config)
      - name: kubeconfig
        value: $(params.kubeconfig)
      - name: ztp-tag
        value: $(params.ztp-tag)
    workspaces:
      - name: ztp
        workspace: ztp

  # Restore Hub Config 
  - name: restore-hub-config 
    taskRef:
      name: spoke-restore-hub-config
    params:
      - name: spokes-config
        value: $(params.spokes-config)
      - name: kubeconfig
        value: $(params.kubeconfig)
      - name: ztp-tag
        value: $(params.ztp-tag)
    runAfter:
      - pre-flight
    workspaces:
      - name: ztp
        workspace: ztp

  # Deploy Spokes 
  - name: deploy-spokes 
    taskRef:
      name: spoke-deploy-spoke 
    params:
      - name: spokes-config
        value: $(params.spokes-config)
      - name: kubeconfig
        value: $(params.kubeconfig)
      - name: ztp-tag
        value: $(params.ztp-tag)
    runAfter:
      - restore-hub-config 
    workspaces:
      - name: ztp
        workspace: ztp

  # Deploy ICSP Spokes Pre
  - name: deploy-icsp-spokes-pre
    taskRef:
      name: spoke-deploy-icsp-spokes-pre
    params:
      - name: spokes-config
        value: $(params.spokes-config)
      - name: kubeconfig
        value: $(params.kubeconfig)
      - name: ztp-tag
        value: $(params.ztp-tag)
    runAfter:
      - deploy-spokes
    workspaces:
      - name: ztp
        workspace: ztp

  # Deploy MetalLB
  - name: deploy-metallb
    taskRef:
      name: spoke-deploy-metallb
    params:
      - name: spokes-config
        value: $(params.spokes-config)
      - name: kubeconfig
        value: $(params.kubeconfig)
      - name: ztp-tag
        value: $(params.ztp-tag)
    runAfter:
      - deploy-icsp-spokes-pre
    workspaces:
      - name: ztp
        workspace: ztp

  # Deploy OCS 
  - name: deploy-ocs
    taskRef:
      name: spoke-deploy-ocs
    params:
      - name: spokes-config
        value: $(params.spokes-config)
      - name: kubeconfig
        value: $(params.kubeconfig)
      - name: ztp-tag
        value: $(params.ztp-tag)
    runAfter:
      - deploy-metallb
    workspaces:
      - name: ztp
        workspace: ztp

  # Deploy Disconnected Registry
  - name: deploy-disconnected-registry
    taskRef:
      name: spoke-deploy-disconnected-registry-spokes
    params:
      - name: spokes-config
        value: $(params.spokes-config)
      - name: kubeconfig
        value: $(params.kubeconfig)
      - name: ztp-tag
        value: $(params.ztp-tag)
      - name: sync
        value: $(params.sync)
    runAfter:
      - deploy-ocs
    workspaces:
      - name: ztp
        workspace: ztp

  # Deploy ICSP Spokes Post
  - name: deploy-icsp-spokes-post
    taskRef:
      name: spoke-deploy-icsp-spokes-post
    params:
      - name: spokes-config
        value: $(params.spokes-config)
      - name: kubeconfig
        value: $(params.kubeconfig)
      - name: ztp-tag
        value: $(params.ztp-tag)
    runAfter:
      - deploy-disconnected-registry
    workspaces:
      - name: ztp
        workspace: ztp

  # Deploy Workers
  - name: deploy-workers
    taskRef:
      name: spoke-deploy-workers
    params:
      - name: spokes-config
        value: $(params.spokes-config)
      - name: kubeconfig
        value: $(params.kubeconfig)
      - name: ztp-tag
        value: $(params.ztp-tag)
    runAfter:
      - deploy-icsp-spokes-post
    workspaces:
      - name: ztp
        workspace: ztp

  # Detach Spoke Cluster
  - name: detach-cluster
    taskRef:
      name: spoke-detach-cluster
    params:
      - name: spokes-config
        value: $(params.spokes-config)
      - name: kubeconfig
        value: $(params.kubeconfig)
      - name: ztp-tag
        value: $(params.ztp-tag)
    runAfter:
      - deploy-workers
    workspaces:
      - name: ztp
        workspace: ztp
