---
- name: Enable libvirtd
  service: name=libvirtd enabled=yes state=started
  ignore_errors: true
  tags: configure-libvirtd

- name: Create libvirtd pool
  command: "kcli create pool -p /var/lib/libvirt/images default"
  ignore_errors: true
  tags: configure-libvirtd

# This step is not needed if the playbook run as root.
# Leaving it here in case it's needed in the future.
#- name: Set pool acl
#  command: "setfacl -m u:$(id -un):rwx /var/lib/libvirt/images"
#  ignore_errors: true
