REGISTRY_TITLE: Kubeframe Registry
FEATURE_USER_INITIALIZE: true
BROWSER_API_CALLS_XHR_ONLY: false
SUPER_USERS:
  - dummy
FEATURE_USER_CREATION: false
EXTERNAL_TLS_TERMINATION: false
PREFERRED_URL_SCHEME: https
CREATE_REPOSITORY_ON_PUSH_PUBLIC: true
