apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: ztpfw-registry
  namespace: ztpfw-registry
spec:
  configBundleSecret: config-bundle-secret
  components:
    - kind: clairpostgres
      managed: false
    - kind: clair
      managed: false
    - kind: mirror
      managed: false
