apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-ztp-edgeclusters-sno
spec:
  description: Tekton Pipeline to deploy ZTPFW Edge-clusters clusters
  params:
    - name: ztp-container-image
      type: string
      default: "quay.io/ztpfw/pipeline:latest"
    - name: kubeconfig
      type: string
    - name: edgeclusters-config
      type: string
    - name: mock
      type: string
      default: "false"
  workspaces:
    - name: ztp
  tasks:

  # Preflight
  - name: pre-flight
    taskRef:
      name: common-pre-flight-edgeclusters
    params:
      - name: edgeclusters-config
        value: $(params.edgeclusters-config)
      - name: kubeconfig
        value: $(params.kubeconfig)
      - name: ztp-container-image
        value: $(params.ztp-container-image)
      - name: mock
        value: $(params.mock)
    workspaces:
      - name: ztp
        workspace: ztp

  # Deploy Edge-clusters
  - name: deploy-edgeclusters
    taskRef:
      name: edgecluster-deploy-edgecluster
    params:
      - name: edgeclusters-config
        value: $(params.edgeclusters-config)
      - name: kubeconfig
        value: $(params.kubeconfig)
      - name: ztp-container-image
        value: $(params.ztp-container-image)
      - name: mock
        value: $(params.mock)
    runAfter:
      - pre-flight
    workspaces:
      - name: ztp
        workspace: ztp

  # Deploy MetalLB
  - name: deploy-metallb
    taskRef:
      name: edgecluster-deploy-metallb
    params:
      - name: edgeclusters-config
        value: $(params.edgeclusters-config)
      - name: kubeconfig
        value: $(params.kubeconfig)
      - name: ztp-container-image
        value: $(params.ztp-container-image)
      - name: mock
        value: $(params.mock)
    runAfter:
      - deploy-edgeclusters
    workspaces:
      - name: ztp
        workspace: ztp


  # Deploy ZTPFWUI
  - name: deploy-ui
    taskRef:
      name: edgecluster-deploy-ui
    params:
      - name: edgeclusters-config
        value: $(params.edgeclusters-config)
      - name: kubeconfig
        value: $(params.kubeconfig)
      - name: ztp-container-image
        value: $(params.ztp-container-image)
      - name: mock
        value: $(params.mock)
    runAfter:
      - deploy-metallb
    workspaces:
      - name: ztp
        workspace: ztp

  # Detach Edge-cluster Cluster
  - name: detach-cluster
    taskRef:
      name: edgecluster-detach-cluster
    params:
      - name: edgeclusters-config
        value: $(params.edgeclusters-config)
      - name: kubeconfig
        value: $(params.kubeconfig)
      - name: ztp-container-image
        value: $(params.ztp-container-image)
      - name: mock
        value: $(params.mock)
    runAfter:
      - deploy-ui
    workspaces:
      - name: ztp
        workspace: ztp
