apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-ztp-hub-cloud
spec:
  description: Tekton Pipeline to deploy ZTPFW Hub Cluster
  params:
    - name: ztp-container-image
      type: string
      default: "quay.io/ztpfw/pipeline:latest"
    - name: kubeconfig
      type: string
    - name: spokes-config
      type: string
    - name: mock
      type: string
      default: "false"
  workspaces:
    - name: ztp
  tasks:

  # Preflight
  - name: pre-flight
    taskRef:
      name: common-pre-flight
    params:
      - name: spokes-config
        value: $(params.spokes-config)
      - name: kubeconfig
        value: $(params.kubeconfig)
      - name: ztp-container-image
        value: $(params.ztp-container-image)
      - name: mock
        value: $(params.mock)
    workspaces:
      - name: ztp
        workspace: ztp

  # Deploy HTTPD Server
  - name: deploy-httpd-server
    taskRef:
      name: hub-deploy-httpd-server
    params:
      - name: spokes-config
        value: $(params.spokes-config)
      - name: kubeconfig
        value: $(params.kubeconfig)
      - name: ztp-container-image
        value: $(params.ztp-container-image)
      - name: mock
        value: $(params.mock)
    runAfter:
      - pre-flight
    workspaces:
      - name: ztp
        workspace: ztp

  # Deploy Disconnected Registry + Sync
  - name: deploy-disconnected-registry
    taskRef:
      name: hub-deploy-disconnected-registry
    params:
      - name: spokes-config
        value: $(params.spokes-config)
      - name: kubeconfig
        value: $(params.kubeconfig)
      - name: ztp-container-image
        value: $(params.ztp-container-image)
      - name: mock
        value: $(params.mock)
    runAfter:
      - deploy-httpd-server
    workspaces:
      - name: ztp
        workspace: ztp