bases:
  - common
  - hub
  - edgeclusters
  - contrib
resources:
  - deploy-ztp-hub.yaml
  - deploy-ztp-hub-mce.yaml
  - deploy-ztp-edgeclusters.yaml
  - deploy-ztp-edgeclusters-sno.yaml
  - deploy-openshift-ztp.yaml

namespace: edgecluster-deployer
