FROM registry.access.redhat.com/ubi8/nodejs-16:latest as builder
USER root
RUN corepack enable yarn

WORKDIR /app
RUN node --version
RUN yarn --version

COPY ./ui/frontend ./frontend
COPY ./ui/backend ./backend
COPY ./ui/package.json ./ui/yarn.lock ./

# Just to get latest SHA at the build time. Remove it right after.
COPY ./.git ./.git
RUN cd ./frontend ; yarn get-sha ; cd ../ ; rm -rf ./git

# Clean the project when built from sources under development
RUN yarn clean

# Reduce flakiness. The NPM registry network operations can fail sometimes ...
RUN yarn install --frozen-lockfile || (sleep 5 ; yarn install --frozen-lockfile) || (sleep 5 ; yarn install --frozen-lockfile)

RUN yarn test-backend
RUN yarn test-frontend
RUN yarn build-backend
RUN yarn build-frontend

#############
FROM registry.access.redhat.com/ubi8/nodejs-16-minimal:latest
USER root
RUN microdnf install -y httpd-tools openssl ; microdnf clean all

WORKDIR /app
ENV NODE_ENV production

COPY --from=builder /app/backend/build ./
COPY --from=builder /app/backend/node_modules ./node_modules/
COPY --from=builder /app/frontend/build ./client/

EXPOSE 3000
USER 1001

CMD ["node", "./index.js"]
