---
- name: Install chronyd
  package: name=chrony state=present
  ignore_errors: true
  tags: configure-chronyd

- name: Enable chronyd
  service: name=chronyd enabled=yes state=started
  ignore_errors: true
  tags: configure-chronyd

- name: Force time sync
  shell: chronyc -a 'burst 4/4'
  ignore_errors: true
  tags: configure-chronyd
