---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    cluster.ocs.openshift.io/local-devices: "true"
    uninstall.ocs.openshift.io/cleanup-policy: delete
    uninstall.ocs.openshift.io/mode: graceful
  name: mcg-storagecluster
  namespace: openshift-storage
spec:
  multiCloudGateway:
    dbStorageClassName: odf-lvm-vg1
    reconcileStrategy: standalone
  resources:
    noobaa-core:
      limits:
        cpu: 4
        memory: 8Gi
    noobaa-db:
      limits:
        cpu: 4
        memory: 8Gi
    noobaa-endpoint:
      limits:
        cpu: 4
        memory: 8Gi
