---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: ztpfw-registry
spec:
  volumeMode: Filesystem
  resources:
    requests:
      storage: 600Gi
  accessModes:
    - ReadWriteOnce
