apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: spoke-deploy-icsp-spokes-pre
  annotations:
    description: |
      This task will deploy the ICSP on the spoke cluster to point to the Hub's images and work as a disconnected one.
spec:
  workspaces:
    - name: ztp
  params:
    - name: ztp-container-image
      type: string
      default: "quay.io/jparrill/ztp-pipeline:latest"
    - name: kubeconfig
      type: string
      default: ""
    - name: spokes-config
      type: string
      default: ""
  stepTemplate:
    env:
      - name: WORKDIR
        value: "/workspace/ztp"
      - name: SPOKES_CONFIG
        value: $(params.spokes-config)
      - name: KUBECONFIG
        value: "$(workspaces.ztp.path)/kubeconfig"
      - name: DEPLOY_SPOKES_DIR
        value: "deploy-spoke"
      - name: DEPLOY_REGISTRY_DIR
        value: "deploy-disconnected-registry"
      - name: SHARED_DIR
        value: "shared-utils"
  steps:
    - name: deploy-icsp-spokes-pre
      image: "$(params.ztp-container-image)"
      imagePullPolicy: Always
      script: |
        #!/usr/bin/bash

        cd ${WORKDIR}/${DEPLOY_SPOKES_DIR}
        ./configure_disconnected.sh 'spoke' 'pre'
