apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: spoke-deploy-workers
  annotations:
    description: |
      This task will deploy the worker in the Spoke Cluster.
spec:
  workspaces:
    - name: ztp
  params:
    - name: ztp-container-image
      type: string
      default: "quay.io/jparrill/ztp-pipeline:latest"
    - name: config-file-path
      type: string
      default: ""
    - name: spokes-config
      type: string
      default: ""
  stepTemplate:
    env:
      - name: WORKDIR
        value: "/ztp-pipeline"
      - name: SPOKES_CONFIG
        value: $(params.spokes-config)
      - name: KUBECONFIG
        value: "$(workspaces.ztp.path)/kubeconfig"
      - name: DEPLOY_WORKER_DIR
        value: "deploy-worker"
  steps:
    - name: deploy-worker
      image: "$(params.ztp-container-image)"
      imagePullPolicy: Always
      script: |
        #!/usr/bin/bash

        cd ${WORKDIR}/${DEPLOY_WORKER_DIR}
        ./render_worker.sh
