---
- name: Use DNF fastest mirror
  ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: fastestmirror
    value: 1
  when: os == "fedora"

- name: Use DNF drpm
  ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: deltarpm
    value: true
  when: os == "fedora"

- name: Use DNF parallel downloads
  ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: max_parallel_downloads
    value: 20
  when: os == "fedora"

- name: Uninstall packages
  package: name={{ item }} state=absent
  with_items:
    - golang
    - motd-news-config
    - command-not-found
    - update-notifier-common
  ignore_errors: true

- name: Enable copr repo karmab/kcli
  command: "dnf copr enable -y karmab/kcli"
  ignore_errors: true
  when: os == "fedora"

- name: Enable EPEL repository
  package: name=epel-release state=present
  ignore_errors: true
  when: os == "fedora"

- name: Install common packages
  package: name={{ item }} state=present
  with_items:
    - bash-completion
    - bc
    - sysstat
    - tmux
    - curl
    - util-linux
    - tuned
    - cmake
    - mc
    - nmap
    - tar
    - unzip
    - rsync
    - net-tools
    - logrotate
    - make
    - wget
    - git
    - jq
    - mlocate
    - libvirt
    - qemu-kvm-core
    - kcli
    - skopeo
    - firewalld
    - bind-utils
    - httpd-tools
    - joe
    - ansible
    - podman
    - spice-server
    - spice-protocol
    - qemu-kvm-ui-spice
  ignore_errors: true

- name: Enable common services
  service: name={{ item }} enabled=yes state=started
  with_items:
    - tuned
    - fstrim.timer
    - firewalld
  ignore_errors: true

- name: Set tuned profile to latency-performance
  shell: /usr/sbin/tuned-adm profile latency-performance
  notify: Restart tuned

- name: Configure logrotate.conf
  lineinfile:
    dest: /etc/logrotate.conf
    create: true
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^compress", line: "compress" }
    - { regexp: "^rotate.*", line: "rotate 14" }
    - { regexp: "^daily", line: "daily" }
    - { regexp: "^weekly.*", line: "" }
    - { regexp: "^dateext.*", line: "" }
