---
- name: Install SSH keys from github.com/USER.keys
  authorized_key:
    user: "root"
    key: "https://github.com/{{ item }}.keys"
  with_items:
    - "{{ users }}"
  when: updatesshkeys==True

- name: Disable root login over ssh with password
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin .*"
    state: present
    line: "PermitRootLogin prohibit-password"
  notify:
    - Restart sshd

- name: Disable password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication .*"
    state: present
    line: "PasswordAuthentication no"
  when: sshpassword==False
  notify:
    - Restart sshd

- name: Enable password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication .*"
    state: present
    line: "PasswordAuthentication yes"
  when: sshpassword==True
  notify:
    - Restart sshd

- name: SSH Listen on all interfaces
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^ListenAddress .*"
    state: absent
  notify:
    - Restart sshd
