---
- name: Install helpful packages
  package: name={{ item }} state=present
  with_items:
    - fail2ban
  ignore_errors: true
  when: sshpassword==True

- name: Configure fail2ban for SSH
  ini_file:
    path: /etc/fail2ban/jail.conf
    section: sshd
    option: enabled
    value: true

- name: Enable fail2ban
  service: name={{ item }} enabled=yes state=started
  with_items:
    - fail2ban
  when: sshpassword==True
  ignore_errors: true

- name: Disable fail2ban
  service: name={{ item }} enabled=no state=stopped
  with_items:
    - fail2ban
  when: sshpassword==False
  ignore_errors: true
