name: Set MOTD
on:
  pull_request_review:
    types: [submitted, edited]
  pull_request:
    types: [labeled]
  workflow_dispatch:

jobs:
  full-stack-testing:
    if: github.event.review.state == 'approved'  && !contains(github.event.label.name, 'skip-ci') || github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'test-ci')
    runs-on: CI-pool
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: ${{github.event.pull_request.head.repo.full_name}}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set MOTD
        run: |
          /root/bin/set-motd set -user "ZTPFW Github Actions" -pr "${{ github.event.pull_request.number }}" -motd "${{ github.event.pull_request.pull_request }}"
