name: "User Interface"

on:
  pull_request:
    paths:
      - 'ui/**'
    types: [labeled,synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: (!contains(github.event.label.name, 'skip-ci-ui') && !contains(github.event.pull_request.labels.*.name, 'skip-ci-ui')) || github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'test-ci-ui')
    continue-on-error: true
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max-old-space-size=8192'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            /home/runner/.cache/yarn/v6
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/ui/yarn.lock/*') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Yarn hack
        run: mkdir -p /home/runner/.cache/yarn/v6
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: './ui/yarn.lock'
      - name: Install dependencies
        run: yarn install
        working-directory: ./ui
      - name: Test frontend
        run: yarn test-frontend
        working-directory: ./ui
      - name: Test backend
        run: yarn test-backend
        working-directory: ./ui
      - name: Build frontend
        run: yarn build-frontend
        working-directory: ./ui
      - name: Build frontend
        run: yarn build-backend
        working-directory: ./ui
