#
# Copyright 2023 Red Hat Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing permissions and limitations under the
# License.
#

FROM registry.access.redhat.com/ubi9/ubi:9.1.0-1750 AS builder

# Install the Go toolset:
RUN \
    curl --location --retry 5 --output /tmp/tarball https://go.dev/dl/go1.20.linux-amd64.tar.gz && \
    echo 5a9ebcc65c1cce56e0d2dc616aff4c4cedcfbda8cc6f0288cc08cda3b18dcbf1 /tmp/tarball | sha256sum --check && \
    tar --directory /usr/local --extract --file /tmp/tarball && \
    rm /tmp/tarball

# Create the builder user:
RUN \
    useradd builder
USER \
    builder
ENV \
    CGO_ENABLED="0" \
    PATH="${PATH}:/usr/local/go/bin"
WORKDIR \
    /home/builder

# Copy the source code into the container:
COPY . .

# Run the build:
RUN go build

FROM scratch

# Copy the binary from the builder image:
COPY --from=builder /home/builder/ztp /ztp

# Set the entry point:
ENTRYPOINT ["/ztp"]
